/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lowcodemendix.developer;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.List;
import java.util.Arrays;
import java.util.HashSet;


class AppTest {
    @Test
    void testSingleCharacter() {
        char[] input = {'a'};
        List<String> expected = Arrays.asList("a");
        List<String> actual = PermutationGenerator.permute(input, 0, input.length);
        assertEquals(new HashSet<>(expected), new HashSet<>(actual));
    }

    @Test
    void testTwoCharacters() {
        char[] input = {'a', 'b'};
        List<String> expected = Arrays.asList("ab", "ba");
        List<String> actual = PermutationGenerator.permute(input, 0, input.length);
        assertEquals(new HashSet<>(expected), new HashSet<>(actual));
    }

    @Test
    void testThreeCharacters() {
        char[] input = {'a', 'b', 'c'};
        List<String> expected = Arrays.asList("abc", "acb", "bac", "bca", "cab", "cba");
        List<String> actual = PermutationGenerator.permute(input, 0, input.length);
        assertEquals(new HashSet<>(expected), new HashSet<>(actual));
    }

    @Test
    void testDuplicateCharacters() {
        char[] input = {'a', 'a', 'b', 'b'};
        List<String> expected = Arrays.asList("aabb", "abab", "abba", "baab", "baba", "bbaa");
        List<String> actual = PermutationGenerator.permute(input, 0, input.length);
        assertEquals(new HashSet<>(expected), new HashSet<>(actual));
    }
}
